version: "3.8"

services:
  frontend:
    image: ghcr.io/nastiasolo/frontend:latest
    env_file:
      - ./frontend/.env
    volumes:
      - frontend_build:/app/dist
    depends_on:
      - backend

  backend:
    image: ghcr.io/nastiasolo/backend:latest
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: prac
      POSTGRES_DB: prac
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "prac"]
      interval: 3s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:6.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  nginx:
    image: ghcr.io/nastiasolo/nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

networks:
  default:
    name: app_net

volumes:
  frontend_build:
  postgres_data:
  pgadmin_data:
